### ISSUE TITLE
Cannot open solution in Visual Studio 2013

### ISSUE THREAD

**Issue by MathieuDSTP** [RolandPheasant/Dynamic.Trader#6]
I get that in the in visual studio console after it refuses to open the projects inside the solution.
--
C:\Code\Dynamic.Trader\Trader.Domain\Trader.Domain.csproj : error  : The attribute "Version" in element <PackageReference> is unrecognized.  C:\Code\Dynamic.Trader\Trader.Domain\Trader.Domain.csproj

C:\Code\Dynamic.Trader\Trader.Client\Trader.Client.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Code\Dynamic.Trader\Trader.Client\Trader.Client.csproj
--

**Comment by RolandPheasant** [comment]
Dynamic trader has been upgraded to use the new visual studio 2017 project style. This is why it cannot be opened in Vs 2013.

I have created a branch: version4 which is based off the commit just before I upgraded it. Please give it a go.

Dynamic trader is a sample app and I will not be maintaining compatability for earlier vs. if the branch does not work you can install Vs community edition for free

**Comment by DingpingZhang** [comment]
Hi, @RolandPheasant 

Could you tell me how to create a project with "the new visual studio 2017 project style"?

I have a puzzle: all .Net framework projects I create use "References", rather than "Dependencies", to manage packages. 

Thank you!

**Comment by glennawatson** [comment]
You should just be able to open it up in Visual Studio 2017 and it'll work. 

If you want to use the new VS 2017 project, you can create a .net standard project from VS 2017. 

See here for a guide 
https://natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/
